env:
  es2020: true
  node: true
extends:
  - google
  - 'plugin:editorconfig/noconflict'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - editorconfig
rules:
  'editorconfig/editorconfig': error
